services:
  postgres:
    image: supabase/postgres:17.6.1.008
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: supabase_admin
      POSTGRES_PASSWORD: c0d3ly7v
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./databases:/docker-entrypoint-initdb.d

volumes:
  db_data:
